import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import Link from 'next/link'
export default function Home() {
  const { data: session, status } = useSession()
  if (status === 'authenticated') {
    return (
      <>
        <Head>
          <title>About - SVEAS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <nav className='nav'>
            <ul className='nav-list'>
              <li><Link href='/'>Back</Link></li>
              <li className='nav-title'>About SVEAS</li>
            </ul>
          </nav>
          <p>S.V.E.A.S. is a notification system that allows transmission of SMS data using a transmitter device to be used in case of accident which is connected to the notification device that is assigned to the rescue team that can immediately recognize as an alert notification of possible accident in the sea and providing accurate information such as the exact coordinates of the area of accident. </p>
        </div>
      </>
      
    )
  }
}
