import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import Link from 'next/link'
export default function Home() {
  const { data: session, status } = useSession()
  if (status === 'authenticated') {
    return (
      <>
        <Head>
          <title>About - SVEAS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <nav className='nav'>
            <ul className='nav-list'>
              <li><Link href='/'>Back</Link></li>
              <li className='nav-title'>About SVEAS</li>
            </ul>
          </nav>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eligendi beatae esse amet totam quia animi, necessitatibus qui ratione, ab quasi dolorem. Velit error aspernatur sint ad voluptas consequuntur labore illo?</p>

        </div>
      </>
      
    )
  }
}
